<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 ./Tree.glb -t
Author: Sahir Virmani (https://sketchfab.com/sahirvirmani)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/giant-low-poly-tree-acfd2b7f80894848b56c2ac8e7e59572
Title: Giant Low Poly Tree
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Cylinder_0: THREE.Mesh
      Icosphere_0: THREE.Mesh
      Icosphere001_0: THREE.Mesh
      Icosphere002_0: THREE.Mesh
      Icosphere003_0: THREE.Mesh
      Icosphere004_0: THREE.Mesh
      Icosphere005_0: THREE.Mesh
    }
    materials: {
      tree_wood: THREE.MeshStandardMaterial
      ['leaf_green.003']: THREE.MeshStandardMaterial
      ['leaf_green.004']: THREE.MeshStandardMaterial
      ['leaf_green.001']: THREE.MeshStandardMaterial
      leaf_green: THREE.MeshStandardMaterial
      ['leaf_green.002']: THREE.MeshStandardMaterial
      ['leaf_green.005']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/Tree.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={0.41}>
      <T.Mesh geometry={gltf.nodes.Cylinder_0.geometry} material={gltf.materials.tree_wood} scale={[1, 1, 6.69]} />
      <T.Mesh
        geometry={gltf.nodes.Icosphere_0.geometry}
        material={gltf.materials['leaf_green.003']}
        position={[0.03, 1.99, 20.57]}
        scale={2.44}
      />
      <T.Mesh
        geometry={gltf.nodes.Icosphere001_0.geometry}
        material={gltf.materials['leaf_green.004']}
        position={[-12.06, 11.58, 18.51]}
        scale={2.44}
      />
      <T.Mesh
        geometry={gltf.nodes.Icosphere002_0.geometry}
        material={gltf.materials['leaf_green.001']}
        position={[-12.83, -4.37, 18.68]}
        scale={2.44}
      />
      <T.Mesh
        geometry={gltf.nodes.Icosphere003_0.geometry}
        material={gltf.materials.leaf_green}
        position={[13.32, 3.81, 20.57]}
        scale={2.44}
      />
      <T.Mesh
        geometry={gltf.nodes.Icosphere004_0.geometry}
        material={gltf.materials['leaf_green.002']}
        position={[5.02, -8, 16.59]}
        scale={2.44}
      />
      <T.Mesh
        geometry={gltf.nodes.Icosphere005_0.geometry}
        material={gltf.materials['leaf_green.005']}
        position={[1.94, 12.6, 17.61]}
        scale={2.44}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
